### ISSUE TITLE
Add Kubenetes validation job to github action

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#12]
# User Story: Kubernetes Manifest Validation Using Kubeconform

## Title
As a DevOps engineer, I need to validate Kubernetes manifests using Kubeconform to ensure they conform to Kubernetes schema specifications before deployment.

## Description
Implement automated Kubernetes manifest validation in our CI pipeline using Kubeconform with arkade for installation and proper reporting capabilities.

### CI/CD Integration
```yaml
validate:
  name: Validate Kubernetes Manifests
  runs-on: ubuntu-22.04
  steps:
    - name: Validate Kubernetes manifests
      run: |
        kubeconform \
          --strict \
          --summary \
          --output json \
          k8s > validation-results/validation.json
```

### Tool Installation
- [ ] Successfully install arkade
- [ ] Install latest version of kubeconform
- [ ] Verify tool accessibility in CI pipeline

### Validation Requirements
- [ ] Validate all manifests in k8s directory
- [ ] Use strict validation mode
- [ ] Check against correct Kubernetes schema versions
- [ ] Validate resource kinds and fields
- [ ] Ensure proper indentation and syntax

### Report Generation
- [ ] Generate JSON format reports
- [ ] Include validation summary
- [ ] Provide detailed error messages
- [ ] Store reports as build artifacts
- [ ] Create readable HTML output

### Workflow Configuration
```yaml
on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/kubeconform.yml'
```

### Directory Structure
```
project/
├── k8s/
│   ├── deployment.yml
│   ├── service.yml
│   └── configmap.yml
└── .github/
    └── workflows/
        └── kubeconform.yml
```

### Validation Results Format
```json
{
  "file": "k8s/deployment.yml",
  "status": "valid",
  "resources": [
    {
      "kind": "Deployment",
      "name": "service-name",
      "status": "valid",
      "version": "apps/v1"
    }
  ]
}
```

## Definition of Done
- [ ] Validation workflow successfully implemented
- [ ] All Kubernetes manifests validated
- [ ] Reports generated in required formats
- [ ] Results stored as artifacts
- [ ] Documentation updated
- [ ] Team trained on interpreting results

### Success Cases
1. Valid Kubernetes manifests pass validation
2. Reports generated correctly
3. Artifacts properly stored

### Failure Cases
1. Invalid schema detection
2. Improper resource definitions
3. Missing required fields
4. Schema version mismatches

## Documentation Requirements
1. Setup instructions
2. Report interpretation guide
3. Common error solutions
4. Workflow maintenance guide

## Success Metrics
- All manifests validated before deployment
- No invalid manifests reaching production
- Clear error reporting
- Actionable feedback for developers

## Team Guidelines
1. Review validation results before merge
2. Fix all validation errors
3. Update documentation for common issues
4. Maintain schema version compatibility

## Performance Requirements
- Validation completes under 2 minutes
- Report generation under 30 seconds
- Artifact upload under 1 minute

## Error Messages
Example error output:
```text
Error: Invalid Deployment manifest
File: deployment.yml
Resource: patient-service
Field: spec.template.spec.containers[0].ports
Error: required field 'containerPort' not found
```

## Report Storage
```yaml
- name: Upload validation results
  if: always()
  uses: actions/upload-artifact@v3
  with:
    name: kubeconform-results
    path: validation-results
    retention-days: 7
```

Would you like me to expand on any particular section of this user story?
