### ISSUE TITLE
Enable GitHub Container Registry

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#15]
# Enable GitHub Container Registry for Microservices

## Description
As a DevOps engineer, I want to set up GitHub Container Registry (GHCR) for our microservices, so we can securely store and distribute Docker images within our GitHub organization.

## Acceptance Criteria
- [ ] Enable GHCR in GitHub organization settings
- [ ] Configure PAT with package permissions
  - `write:packages`
  - `delete:packages`
  - `read:packages`
- [ ] Update CI/CD pipeline to:
  - Authenticate with GHCR
  - Build Docker images
  - Push images to GHCR
  - Tag images with commit SHA and latest
- [ ] Update Kubernetes manifests to pull from GHCR
- [ ] Document setup process for team

## Documentation Tasks
- [ ] Create step-by-step setup guide
- [ ] Add troubleshooting section
- [ ] Include examples of common operations
- [ ] Document security best practices

## Technical Tasks
1. Configure GitHub Actions workflow:
 
   # Add to the jobs section of the Commit Stage workflow

  ```yaml
build-and-push:
    needs: [validate, detect-changes]  # Add dependency on validate job
    strategy:
      matrix:
        service: [patient-service, config-service]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check if service should run
        id: should-run
        run: |
          if [[ "${{ matrix.service }}" == "patient-service" && "${{ needs.detect-changes.outputs.patient-service }}" == "true" ]] || \
             [[ "${{ matrix.service }}" == "config-service" && "${{ needs.detect-changes.outputs.config-service }}" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.should-run.outputs.should_run == 'true'
        uses: actions/checkout@v4

      - name: Log in to GHCR
        if: steps.should-run.outputs.should_run == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.should-run.outputs.should_run == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push
        if: steps.should-run.outputs.should_run == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

2. Update Kubernetes manifest:
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: patient-service
   spec:
     template:
       spec:
         containers:
         - name: patient-service
           image: ghcr.io/organization/patient-service:latest
           imagePullPolicy: Always
         imagePullSecrets:
```
Create Personal Access Token (PAT):

Go to GitHub Settings > Developer settings > Personal access tokens > Tokens (classic)
Generate new token with these permissions:

write:packages
delete:packages
read:packages

Login to GitHub Container Registry:

bashCopyecho $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin

Configure Gradle build:

kotlinCopy// build.gradle.kts
docker {
    name = "ghcr.io/${project.property("github.username")}/${project.name}"
    tags.set(listOf("latest"))
}

Add secrets to GitHub repository:

REGISTRY_USERNAME: GitHub username
REGISTRY_PASSWORD: PAT created in step 1

Update GitHub Actions workflow:

yamlCopyjobs:
  build:
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

Make repository public in package settings to allow pulling without authentication.
