### ISSUE TITLE
Create Github action workflow

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#2]
As a developer, when the code is pushed on any branch, it should run a workflow that includes:

- Testing
- Vulnerability scanning

```
name: Commit Stage
on: push

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      config-service: ${{ steps.filter.outputs.config-service }}
      patient-service: ${{ steps.filter.outputs.patient-service }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            config-service:
              - 'config-service/**'
            patient-service:
              - 'patient-service/**'

  build-and-test:
    needs: detect-changes
    strategy:
      matrix:
        service: [config-service, patient-service]
    if: ${{ needs.detect-changes.outputs[matrix.service] == 'true' }}
    name: Build and Test ${{ matrix.service }}
    runs-on: ubuntu-22.04
    environment: development
    permissions:
      contents: read
    env:
      DB_URL: ${{ secrets.DB_URL_DEV }}
      DB_USERNAME: ${{ secrets.DB_USERNAME_DEV }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      
      - name: Build, unit tests and integration tests
        working-directory: ${{ matrix.service }}
        run: |
          chmod +x gradlew
          ./gradlew build
      
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.service }}
          path: |
            ${{ matrix.service }}/build/reports/tests/test/
            ${{ matrix.service }}/build/reports/tests/integrationTest/
            ${{ matrix.service }}/build/reports/jacoco/test/html/
            ${{ matrix.service }}/build/reports/checkstyle/
          retention-days: 1

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.service }}
          path: ${{ matrix.service }}/build/libs/
          retention-days: 1

  security-scan:
    needs: build-and-test
    strategy:
      matrix:
        service: [config-service, patient-service]
    if: ${{ needs.detect-changes.outputs[matrix.service] == 'true' }}
    name: Security Scan ${{ matrix.service }}
    runs-on: ubuntu-22.04
    environment: development
    permissions:
      contents: read
      security-events: write
    env:
      DB_URL: ${{ secrets.DB_URL_DEV }}
      DB_USERNAME: ${{ secrets.DB_USERNAME_DEV }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}/${{ matrix.service }}"
          fail-build: false
          severity-cutoff: high
          
      - name: Upload Dependency Check Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports-${{ matrix.service }}
          path: ${{ matrix.service }}/build/reports/dependency-check-report.html
          retention-days: 1
  
  report-upload:
    name: Upload Security Report
    needs: [security-scan, detect-changes]
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    if: success() || failure()
    steps:
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ needs.security-scan.outputs.sarif }}

      - name: Download All Reports
        uses: actions/download-artifact@v3
        with:
          path: all-reports

      - name: Upload Combined Reports
        uses: actions/upload-artifact@v3
        with:
          name: all-reports
          path: all-reports
          retention-days: 7
```
