### ISSUE TITLE
Create Secrets ConfigMaps and RBAC file for Patient-Service

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#28]
# Patient Service Migration to Kubernetes

## Background
The current patient service runs as a traditional application with static configurations. This setup requires application restarts for configuration changes, causing service disruptions. We need to modernize the service to be Kubernetes-native to improve resilience and maintainability.

## Technical Description
We need to integrate Spring Cloud Kubernetes into our patient service, implementing proper RBAC controls and configuration management through Kubernetes ConfigMaps.

## Acceptance Criteria
1. Spring Cloud Kubernetes Integration
   - Dependencies added to build.gradle.kts
   - Application configured to read from Kubernetes ConfigMap
   - @RefreshScope implemented for dynamic configuration updates

2. Security Implementation
   - Service account created for patient service
   - RBAC role defined with minimal required permissions
   - Role binding configured correctly
   - Security audit passed

3. Deployment Configuration
   - ConfigMap properly mounted in deployment
   - Graceful shutdown configured
   - Resource limits defined
   - Health check endpoints implemented

4. Documentation
   - Deployment process documented
   - Configuration update procedure written
   - Troubleshooting guide created

## Definition of Done
- All code reviewed and merged
- Integration tests passing

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-kubernetes-client

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-kubernetes-client-config

## Developer steps
1. Add dependencies to `patient-service/build.gradle.kts`:
```kotlin
dependencies {
    implementation("org.springframework.cloud:spring-cloud-starter-kubernetes-client")
    implementation("org.springframework.cloud:spring-cloud-starter-kubernetes-client-config")
}
```

2. Create ConfigMap file in `patient-service/k8s/config.yml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service
data:
  application.yml: |
    server:
      port: 8080
      shutdown: graceful
    # ... rest of your configuration
```

3. Create RBAC file in `patient-service/k8s/rbac.yml`:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patient-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-reader
subjects:
- kind: ServiceAccount
  name: patient-service
roleRef:
  kind: Role
  name: config-reader
  apiGroup: rbac.authorization.k8s.io
```

4. Update `patient-service/k8s/deployment.yml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  template:
    spec:
      serviceAccountName: patient-service
      containers:
        - name: patient-service
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: patient-service
```

5. Add @RefreshScope to `patient-service/src/main/java/com/hospital/patient/PatientServiceApplication.java`:
```java
@RefreshScope
@SpringBootApplication
public class PatientServiceApplication { ... }
```

6. The verification commands should now reference the correct paths:
```bash
# Apply configurations from the k8s directory
kubectl apply -f patient-service/k8s/rbac.yml
kubectl apply -f patient-service/k8s/config.yml
kubectl apply -f patient-service/k8s/deployment.yml
kubectl apply -f patient-service/k8s/service.yml

# The rest of the verification commands remain the same since they interact 
# with Kubernetes resources rather than files
kubectl get configmap patient-service -o yaml
kubectl get serviceaccount patient-service
kubectl get role config-reader
kubectl get rolebinding config-reader
kubectl get pods
kubectl describe pod <pod-name>
kubectl logs <pod-name>
kubectl edit configmap patient-service
curl -X POST http://localhost:8001/actuator/refresh
```
