### ISSUE TITLE
Add graceful shutdown to config repo and patient service

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#29]
# Issue: Configure Graceful Shutdown for Patient Service

## Problem Statement
The patient service needs proper graceful shutdown configuration to ensure reliable operation in a Kubernetes environment. Without explicit shutdown timing configuration, the service may not properly handle in-flight requests during pod termination, potentially affecting patient data processing.

## Current State
The service is configured with basic application properties but lacks specific shutdown timing controls. When Kubernetes initiates a pod termination, the application relies on default timeout values which may not align with our operational needs.

## Proposed Changes
Add Spring lifecycle configuration to control the graceful shutdown process:

```yaml
spring:
  application:
    name: patient-service  # Identifies our service in the Kubernetes cluster
  lifecycle:
    timeout-per-shutdown-phase: 15s  # Allows adequate time for request completion
```

## Technical Details
The `timeout-per-shutdown-phase` setting affects how Spring Boot handles the shutdown process:

1. When shutdown begins:
   - Application stops accepting new requests
   - Existing requests have 15 seconds to complete
   - Application begins graceful termination of active components

2. Interaction with Kubernetes:
   - Aligns with Kubernetes pod termination grace period
   - Provides predictable behavior during rolling updates
   - Ensures proper cleanup of resources

## Implementation Notes
1. Add configuration to `application.yml`
2. Consider aligning with other timeout settings:
   ```yaml
   server:
     shutdown: graceful
     tomcat:
       keep-alive-timeout: 15s  # Should match or be less than shutdown timeout
   ```

## Testing Plan
1. Verify shutdown behavior:
   ```bash
   # Deploy service with new configuration
   kubectl apply -f deployment.yml

   # Trigger a rolling update
   kubectl rollout restart deployment patient-service

   # Monitor logs during shutdown
   kubectl logs -f <pod-name>
   ```

2. Test under load:
   - Generate concurrent requests
   - Initiate pod termination
   - Verify all requests complete or fail gracefully

## Expected Outcomes
- Clean service termination during deployments
- No request failures during rolling updates
- Predictable shutdown timing
- Improved monitoring of shutdown process

## Acceptance Criteria
- [ ] Configuration applied and validated in all environments
- [ ] No errors during pod termination
- [ ] All in-flight requests handled appropriately
- [ ] Monitoring shows clean shutdown process
- [ ] Documentation updated with new configuration details

## References
- [Spring Boot Graceful Shutdown](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown)
- [Kubernetes Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)
