### ISSUE TITLE
Update Port Configuration and Add Management Endpoints for Patient Service

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#30]
# Update Port Configuration and Add Management Endpoints for Patient Service

## Background
Our patient service requires port configuration updates to align with our new microservices architecture. Additionally, we need to expose management endpoints through a dedicated port for better operational monitoring and control.

### 1. Patient Service Main Port Update
Updating the service port from 8080 to 9020 in `patient-service.yml`:
```yaml
server:
  port: 9010
  shutdown: graceful
  tomcat:
    # existing tomcat configuration remains
```

### 2. Management Port Configuration
Adding dedicated management port in `config.yml`:
```yaml
management:
  server:
    port: 8010  # Separate port for actuator endpoints
  endpoints:
    web:
      exposure:
        include: [
          "health",
          "metrics", 
          "prometheus",
          "refresh",
          "info",
          "env",
          "mappings",
          "beans"
        ]
```

### 3. Kubernetes Deployment Updates
Updating container port configuration in deployment manifest:
```yaml
spec:
  template:
    spec:
      containers:
        - name: patient-service
          ports:
            - containerPort: 9010  # Main application port
            - containerPort: 8010  # Management port
            - containerPort: 5005  # Debug port
```

## Implementation Notes
1. The port changes require updates in multiple files to maintain consistency
2. Exposed actuator endpoints need to be secured appropriately
3. Debugging port (5005) remains unchanged for development purposes

## Testing Plan
1. Verify service accessibility:
```bash
# Test main application endpoint
curl http://localhost:9020/api/patients

# Test management endpoint
curl http://localhost:9001/actuator/health
```

2. Verify Kubernetes deployment:
```bash
# Check pod status and port bindings
kubectl get pods -l app=patient-service
kubectl describe pod <pod-name>

# Verify port forwarding
kubectl port-forward service/patient-service 9020:9020
kubectl port-forward service/patient-service 9001:9001
```

## Deployment Steps
1. Update configuration files
2. Build new service image
3. Apply Kubernetes configurations:
```bash
kubectl apply -f deployment.yml
kubectl apply -f service.yml
kubectl apply -f config.yml
```

## Acceptance Criteria
- [ ] Service accessible on port 9020
- [ ] Management endpoints available on port 9001
- [ ] All actuator endpoints functioning correctly
- [ ] Kubernetes deployment successful with correct port mappings

Change management port in config.yml file 

```
management:
  server:
    port: 9001  # Added this line to set actuator port
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus", "refresh", "info", "env", "mappings", "beans"]
```

Full file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: patient-service
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9020
            - containerPort: 9001
            - containerPort: 5005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```
