### ISSUE TITLE
Kafka Setup Guide for Spring Boot Microservice

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#42]
## Story Points
8

## Priority
High

## Developer setup

# Kafka Setup Guide for Spring Boot Microservice

## 1. Add Dependencies (build.gradle.kts)
```kotlin
dependencies {
    implementation("org.apache.kafka:kafka-clients:3.9.0")
    // Add other Kafka-related dependencies as needed
}
```

## 2. Create Docker Compose Configuration
Create a `docker-compose.yml` in project root:
```yaml
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
```

## 3. Update Application Configuration
Add Kafka configuration to application.yml:
```yaml
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: appointment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
```

## 4. Create Kubernetes ConfigMap
Add to existing ConfigMap:
```yaml
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: appointment-service-group
      auto-offset-reset: earliest
```

## 5. Topic Creation
Create a script for topic initialization:
```bash
#!/bin/bash
kafka-topics.sh --create \
  --topic appointment-events \
  --bootstrap-server broker:29092 \
  --partitions 3 \
  --replication-factor 1
```

## 6. Testing Setup
```bash
# Start Kafka
docker-compose up -d

# Verify Kafka is running
docker logs broker

# Create test topic
docker exec -it broker kafka-topics.sh --create \
  --topic test-topic \
  --bootstrap-server broker:29092
```

## 7. Monitoring Setup
Add to prometheus.yml:
```yaml
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:9092']
```

Add to existing Grafana configuration:
- Kafka dashboard for metrics
- JVM metrics for Kafka
- Producer/Consumer metrics

## Notes:
- Uses KRaft mode (no ZooKeeper required)
- Development configuration only
- For production:
  - Increase replication factor
  - Configure security
  - Adjust performance parameters
  - Set up proper monitoring

```ini
dependencies {
    // Base Kafka
    implementation("org.apache.kafka:kafka-clients:3.9.0")
    
    // Spring Kafka
    implementation("org.springframework.kafka:spring-kafka:3.1.1")
    testImplementation("org.springframework.kafka:spring-kafka-test:3.1.1")
    
    // For Reactive Kafka
    implementation("io.projectreactor.kafka:reactor-kafka:1.3.23")
    
    // For JSON serialization/deserialization
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0") // For Java 8 date/time support
    
    // Testing
    testImplementation("io.projectreactor:reactor-test")
    testImplementation("org.testcontainers:kafka:1.19.6")
}
```

From the documents, for a basic Gradle setup with Kafka:

Gradle dependency (basic):

```ini
dependencies {
    implementation("org.apache.kafka:kafka-clients:3.9.0")
}
```

Docker Compose setup (from document 3):

```yml
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
```

To verify setup (from document 3):

bashCopydocker logs broker

Create a test topic:

```bash
docker exec -it broker kafka-topics.sh --create --topic test-topic --bootstrap-server broker:29092
```

Based on the provided documents, I'll create the necessary Java files for the Appointment Service with Kafka integration.

1. `config/KafkaConsumerConfig.java`:
```java
package com.example.appointment.config;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.annotation.EnableKafka;
import org.springframework.kafka.config.ConcurrentKafkaListenerContainerFactory;
import org.springframework.kafka.core.ConsumerFactory;
import org.springframework.kafka.core.DefaultKafkaConsumerFactory;
import java.util.HashMap;
import java.util.Map;

@EnableKafka
@Configuration
public class KafkaConsumerConfig {

    @Bean
    public ConsumerFactory<String, String> consumerFactory() {
        Map<String, Object> configProps = new HashMap<>();
        configProps.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        configProps.put(ConsumerConfig.GROUP_ID_CONFIG, "appointment-group");
        configProps.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        configProps.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        return new DefaultKafkaConsumerFactory<>(configProps);
    }

    @Bean
    public ConcurrentKafkaListenerContainerFactory<String, String> kafkaListenerContainerFactory() {
        ConcurrentKafkaListenerContainerFactory<String, String> factory = new ConcurrentKafkaListenerContainerFactory<>();
        factory.setConsumerFactory(consumerFactory());
        return factory;
    }
}
```

2. `config/KafkaProducerConfig.java`:
```java
package com.example.appointment.config;

import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.StringSerializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.core.DefaultKafkaProducerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.core.ProducerFactory;
import java.util.HashMap;
import java.util.Map;

@Configuration
public class KafkaProducerConfig {

    @Bean
    public ProducerFactory<String, String> producerFactory() {
        Map<String, Object> configProps = new HashMap<>();
        configProps.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        configProps.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        configProps.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        return new DefaultKafkaProducerFactory<>(configProps);
    }

    @Bean
    public KafkaTemplate<String, String> kafkaTemplate() {
        return new KafkaTemplate<>(producerFactory());
    }
}
```

3. `service/KafkaProducerService.java`:
```java
package com.example.appointment.service;

import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;

@Service
public class KafkaProducerService {

    private static final String TOPIC = "appointment_events";
    private final KafkaTemplate<String, String> kafkaTemplate;

    public KafkaProducerService(KafkaTemplate<String, String> kafkaTemplate) {
        this.kafkaTemplate = kafkaTemplate;
    }

    public void sendMessage(String message) {
        kafkaTemplate.send(TOPIC, message);
        System.out.println("Message sent: " + message);
    }
}
```

4. `service/KafkaConsumerService.java`:
```java
package com.example.appointment.service;

import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;

@Service
public class KafkaConsumerService {

    @KafkaListener(topics = "appointment_events", groupId = "appointment-group")
    public void consume(String message) {
        System.out.println("Message received: " + message);
    }
}
```

5. `controller/KafkaController.java`:
```java
package com.example.appointment.controller;

import com.example.appointment.service.KafkaProducerService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class KafkaController {

    private final KafkaProducerService kafkaProducerService;

    public KafkaController(KafkaProducerService kafkaProducerService) {
        this.kafkaProducerService = kafkaProducerService;
    }

    @GetMapping("/api/appointments/send")
    public String sendMessage(@RequestParam String message) {
        kafkaProducerService.sendMessage(message);
        return "Message sent successfully";
    }
}
```

6. `AppointmentServiceApplication.java`:
```java
package com.example.appointment;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AppointmentServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(AppointmentServiceApplication.class, args);
    }
}
```

```ini
appointment-service/
├── src/main/java/com/example/appointment/
│   ├── AppointmentServiceApplication.java
│   ├── appointment/
│   │   ├── controller/
│   │   │   └── AppointmentController.java
│   │   ├── model/
│   │   │   └── Appointment.java
│   │   ├── repository/
│   │   │   └── AppointmentRepository.java
│   │   └── service/
│   │       └── AppointmentService.java
│   │
│   └── kafka/
│       ├── config/
│       │   ├── KafkaConsumerConfig.java
│       │   └── KafkaProducerConfig.java
│       ├── controller/
│       │   └── KafkaController.java
│       └── service/
│           ├── KafkaConsumerService.java
│           └── KafkaProducerService.java
```

You're right. Let me show how to properly structure and reference the Appointment across directories:

1. First, create the Appointment model:
```java
// src/main/java/com/example/appointment/appointment/model/Appointment.java
package com.example.appointment.appointment.model;

import java.time.LocalDateTime;

public class Appointment {
    private Long id;
    private String patientId;
    private String providerId;
    private String facilityId;
    private String serviceId;
    private AppointmentType appointmentType;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private AppointmentStatus status;
    private LocalDateTime createdAt;

    // Constructors, getters, setters
}

public enum AppointmentType {
    VIDEO, IN_PERSON, PHONE, INITIAL_VISIT, FOLLOW_UP
}

public enum AppointmentStatus {
    SCHEDULED, CONFIRMED, CHECKED_IN, IN_PROGRESS, COMPLETED, CANCELLED, NO_SHOW
}
```

2. Create a service to handle appointment events:
```java
// src/main/java/com/example/appointment/kafka/service/AppointmentEventService.java
package com.example.appointment.kafka.service;

import com.example.appointment.appointment.model.Appointment;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;

@Service
public class AppointmentEventService {
    private final KafkaTemplate<String, String> kafkaTemplate;
    private final ObjectMapper objectMapper;

    public AppointmentEventService(KafkaTemplate<String, String> kafkaTemplate, ObjectMapper objectMapper) {
        this.kafkaTemplate = kafkaTemplate;
        this.objectMapper = objectMapper;
    }

    public void sendAppointmentCreated(Appointment appointment) {
        try {
            String message = objectMapper.writeValueAsString(appointment);
            kafkaTemplate.send("appointment_created", message);
        } catch (Exception e) {
            throw new RuntimeException("Error sending appointment event", e);
        }
    }
}
```

3. Update the Kafka consumer to handle appointment events:
```java
// src/main/java/com/example/appointment/kafka/service/KafkaConsumerService.java
package com.example.appointment.kafka.service;

import com.example.appointment.appointment.model.Appointment;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;

@Service
public class KafkaConsumerService {
    private final ObjectMapper objectMapper;

    public KafkaConsumerService(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @KafkaListener(topics = "appointment_events", groupId = "appointment-group")
    public void handleAppointment(String message) {
        try {
            Appointment appointment = objectMapper.readValue(message, Appointment.class);
            // Process appointment
            System.out.println("Received appointment: " + appointment);
        } catch (Exception e) {
            throw new RuntimeException("Error processing appointment message", e);
        }
    }
}
```

4. Update the appointment service to use Kafka:
```java
// src/main/java/com/example/appointment/appointment/service/AppointmentService.java
package com.example.appointment.appointment.service;

import com.example.appointment.appointment.model.Appointment;
import com.example.appointment.kafka.service.AppointmentEventService;
import org.springframework.stereotype.Service;

@Service
public class AppointmentService {
    private final AppointmentEventService eventService;

    public AppointmentService(AppointmentEventService eventService) {
        this.eventService = eventService;
    }

    public void createAppointment(Appointment appointment) {
        // Save appointment to database
        // ...
        
        // Send event
        eventService.sendAppointmentCreated(appointment);
    }
}
```

This structure:
- Keeps the Appointment model in the appointment domain
- Uses the model across both appointment and Kafka packages
- Maintains separation of concerns
- Provides proper serialization/deserialization of appointments for Kafka
- Shows how services interact with each other

Would you like me to add any specific functionality to these components?

For a Microservice architecture using Kubernetes, you'll need to consider:

1. Kafka Configuration in Kubernetes
```yaml
# kafka-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_GROUP_ID: "appointment-service-group"
  KAFKA_TOPICS: "appointment_events,appointment_created,appointment_updated"
```

2. Update Application Configuration
```yaml
# application.yml
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
```

3. Service Deployment
```yaml
# appointment-service-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointment-service:latest
        envFrom:
        - configMapRef:
            name: kafka-config
        ports:
        - containerPort: 8080
```

4. Service Discovery
```yaml
# appointment-service.yml
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

5. Inter-service Communication:
- Services communicate through Kafka events
- Use service discovery for direct API calls when needed
- Consider implementing Circuit Breakers for resilience
To set up a Kafka environment using KRaft mode with Docker Compose and integrate it with a Spring Boot Appointment Service, follow these organized steps:

1. Update docker-compose.yml

Add Spring Boot Service:
yaml
Copy
services:
  appointment-service:
    build: ./appointment-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_BOOT_KAFKA_BOOTSTRAP_SERVERS=kafka:9094
    depends_on:
      - kafka
Ensure Kafka Service Configuration:
yaml
Copy
services:
  kafka_b:
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka_b:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
2. Configure Spring Boot Service

Kafka Properties with Retries:
yaml
Copy
spring:
  kafka:
    bootstrap-servers: kafka:9094
    producer:
      retries: 3
      retry-backoff-ms: 5000
    consumer:
      retry:
        enabled: true
        max-attempts: 3
Implement Producer and Consumer Logic:
java
Copy
@Service
public class AppointmentService {

    @Autowired
    private KafkaTemplate<String, String> kafkaTemplate;

    public void sendAppointment(String topic, String message) {
        kafkaTemplate.send(topic, message);
    }

    @KafkaListener(topics = "appointments")
    public void listen(String message) {
        // Handle message
    }
}
3. Ensure Service Readiness

Use Health Checks and Dependencies:
```yaml
Copy
services:
  appointment-service:
    depends_on:
      - kafka
Implement Retry Logic in Spring Boot:
java
Copy
@Retryable(maxAttempts = 3, backoff = @Backoff(delay = 5000))
public void sendAppointment(String topic, String message) {
    // Send logic
}```
4. Verify Connectivity

Use Java Producer to Send Test Messages:
```java
Copy
KafkaProducer<String, String> producer = new KafkaProducer<>(properties);
producer.send(new ProducerRecord<>("appointments", "Test Message"));```
Confirm Consumption in Appointment Service:
Ensure logs show messages being received and processed.
Monitor with Provectus Kafka-UI:
Access http://localhost:8080 to manage topics and monitor message flow.
5. Persist Data

Use Named Volumes:
```yaml
Copy
volumes:
  kafka_data:
    driver: local```
6. Documentation

Keep Notes on Configurations:
Document any specific configurations or troubleshooting steps taken.
Additional Considerations

Security:
Plan to add SSL/TLS and SASL for production environments.
Scalability:
Consider setting up a multi-broker cluster for future scalability.
Topic Management:
Carefully manage topics, considering disabling auto creation in production.
By following these steps, you can successfully integrate Kafka with your Spring Boot Appointment Service using Docker Compose, ensuring a robust and reliable environment for development and testing.


```yaml
version: '3'
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluent/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    depends_on:
      - zookeeper

  appointment-service:
    build: ./appointment-service
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka```



```ini
plugins {
    java
    id("org.springframework.boot") version "2.7.5"
    id("io.spring.dependency-management") version "1.0.15.RELEASE"
    kotlin("jvm") version "1.6.21"
    kotlin("plugin.spring") version "1.6.21"
}

group = "com.hospital"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.kafka:spring-kafka-test")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}```


Step-by-Step Instructions

1. Configure build.gradle.kts

```kotlin
Copy
plugins {
    java
    id("org.springframework.boot") version "2.5.4"
    id("io.spring.dependency-management") version "1.0.11.RELEASE")
}

group = "com.hospital"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.kafka:spring-kafka")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.kafka:spring-kafka-test")
}```
2. Configure application.properties

```properties
Copy
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=hospital-appointment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer```

appointment.topic=hospital-appointments
3. Create Kafka Producer

```java
Copy
package com.hospital.appointment.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

@Component
public class KafkaProducer {

    private final KafkaTemplate<String, String> kafkaTemplate;

    @Autowired
    public KafkaProducer(KafkaTemplate<String, String> kafkaTemplate) {
        this.kafkaTemplate = kafkaTemplate;
    }

    public void sendAppointmentMessage(String topic, String message) {
        kafkaTemplate.send(topic, message);
        System.out.println("Sent message: " + message + " to topic: " + topic);
    }
}```
4. Create Appointment Service

```java
Copy
package com.hospital.appointment.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class AppointmentService {

    private final KafkaProducer kafkaProducer;

    @Value("${appointment.topic}")
    private String topic;

    @Autowired
    public AppointmentService(KafkaProducer kafkaProducer) {
        this.kafkaProducer = kafkaProducer;
    }

    public void bookAppointment(String patientId, String doctorId, String time) {
        String appointmentMessage = "Appointment booked: Patient " + patientId + " with Doctor " + doctorId + " at " + time;
        kafkaProducer.sendAppointmentMessage(topic, appointmentMessage);
    }
}```
5. Create Kafka Consumer

```java
Copy
package com.hospital.appointment.consumer;

import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

@Component
public class AppointmentConsumer {

    @KafkaListener(topics = "${appointment.topic}", groupId = "hospital-appointment-group")
    public void listen(String message) {
        System.out.println("Received appointment message: " + message);
    }
}```
6. Create REST Controller

```java
Copy
package com.hospital.appointment.controller;

import com.hospital.appointment.service.AppointmentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AppointmentController {

    private final AppointmentService appointmentService;

    @Autowired
    public AppointmentController(AppointmentService appointmentService) {
        this.appointmentService = appointmentService;
    }

    @PostMapping("/book-appointment")
    public void bookAppointment(@RequestParam String patientId, @RequestParam String doctorId, @RequestParam String time) {
        appointmentService.bookAppointment(patientId, doctorId, time);
    }
}```
7. Main Application Class

```java
Copy
package com.hospital.appointment;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class HospitalAppointmentApplication {

    public static void main(String[] args) {
        SpringApplication.run(HospitalAppointmentApplication.class, args);
    }
}
```
