### ISSUE TITLE
Containerize Patient service

### ISSUE THREAD

**Issue by DragonStone12** [DragonStone12/general-hospital-system#6]
# User Story: Patient Service Setup and Deployment

## Story Title
As a DevOps engineer, I need to set up and deploy the patient service component of the general hospital system to enable healthcare providers to manage patient information.

## Description
The patient service is a critical component of our hospital system that needs to be properly configured and deployed to both development and production environments. The service must be containerized, scalable, and maintain proper security standards.

### Configuration Management
- [ ] Service is properly named as 'patient-service' in all configuration files
- [ ] Spring Cloud Config client is configured with proper timeouts and retry settings
- [x] Application configuration is externalized via config server

### Development Environment
- [ ] Development environment includes:
  - Debug port (5005) configured and accessible
  - Live reload enabled on port 35730
  - Source code hot-reloading working
- [ ] Docker Compose setup works with memory limit of 512MB
- [ ] All required ports (8001, 8081, 5005) are properly exposed

### Production Environment
- [ ] Dockerfile builds successfully with multi-stage process
- [ ] Production image runs as non-root user (javauser)
- [ ] JVM is configured for container awareness
- [ ] Health checks are properly configured
- [ ] Memory optimization is set to 75% of container RAM

### Kubernetes Deployment
- [ ] Kubernetes deployment manifest correctly names the service
- [ ] Container port 8001 is properly exposed
- [ ] Environment variables are correctly set
- [ ] Graceful shutdown is configured with 5-second delay

### Security
- [ ] Non-root user is implemented in production container
- [ ] Proper file permissions are set
- [ ] No sensitive information is exposed in configurations

### Monitoring
- [ ] Health check endpoint is accessible
- [ ] Management port (8081) is properly configured
- [ ] Basic monitoring endpoints are working

## Technical Details
- Java Version: 21
- Base Images: 
  - Development: gradle:8.5-jdk21
  - Production: eclipse-temurin:21-jre-jammy
- Framework: Spring Boot
- Build Tool: Gradle
- Container Platform: Docker
- Orchestration: Kubernetes

## Dependencies
- Config Server must be running and accessible
- Docker registry must be available
- Kubernetes cluster must be operational
- Network access to port 8888 for config server

## Effort Estimate
- Configuration setup: 2 hours
- Development environment setup: 3 hours
- Production environment setup: 2 hours
- Kubernetes deployment: 2 hours
- Testing and verification: 3 hours
- Documentation: 2 hours
- Total: 14 hours

## Risk Factors
- Config server availability might impact service startup
- Memory constraints might affect performance
- Debug mode in production could pose security risks if not properly managed
- Port conflicts in development environment

## Notes
- Remember to verify all environment-specific configurations
- Document any deviations from standard deployment patterns
- Consider adding monitoring and logging solutions
- Plan for backup and disaster recovery procedures

## Definition of Done
- [ ] All configuration files are properly set up and validated
- [ ] Service successfully builds in both development and production modes
- [ ] Docker images successfully build and run
- [ ] Kubernetes deployment is successful
- [ ] Health checks pass
- [ ] Documentation is complete and accurate
- [ ] All acceptance criteria are met and verified
- [ ] Code review completed
- [ ] Testing completed in all environments

## Original one
```
# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM gradle:7.6-jdk17 AS builder
WORKDIR /workdir/server
COPY build.gradle settings.gradle /workdir/server/
COPY gradle /workdir/server/gradle
# Download dependencies
RUN gradle dependencies --no-daemon

COPY src /workdir/server/src
RUN gradle build --no-daemon

FROM builder AS dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF

# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD ["gradle", "bootRun"]

FROM builder as prepare-production
RUN mkdir -p build/dependency
WORKDIR /workdir/server/build/dependency
RUN jar -xf ../libs/*.jar

FROM eclipse-temurin:17-jre-focal
EXPOSE 8001
VOLUME /tmp
ARG DEPENDENCY=/workdir/server/build/dependency
COPY --from=prepare-production ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=prepare-production ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=prepare-production ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.epoch.podcast.PodcastApplication"]
```

## Updated one
```
# syntax=docker/dockerfile:1.4
FROM gradle:8.5-jdk21 AS builder

WORKDIR /app

# Copy Gradle configuration files first for better layer caching
COPY gradle/ ./gradle/
COPY gradlew build.gradle settings.gradle ./

# Verify Gradle wrapper is executable
RUN chmod +x ./gradlew

# Download dependencies and cache them
RUN ./gradlew dependencies --no-daemon --parallel

# Copy source code after dependency resolution
COPY src/ ./src/

# Build the application
RUN ./gradlew build --no-daemon --parallel

# Development environment setup
FROM builder AS dev-envs

# Combine RUN commands to reduce layers and use proper package installation
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -s /bin/bash -m vscode \
    && groupadd docker \
    && usermod -aG docker vscode

# Install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /

# Use gradlew instead of gradle for consistency
CMD ["./gradlew", "bootRun", "--no-daemon"]

# Prepare for production
FROM builder as prepare-production

WORKDIR /app/build/dependency
RUN mkdir -p . \
    && cd .. \
    && jar -xf libs/*.jar

# Production image
FROM eclipse-temurin:21-jre-jammy

# Create non-root user for security
RUN useradd -r -s /bin/false javauser

WORKDIR /app

# Copy application files
COPY --from=prepare-production /app/build/dependency/BOOT-INF/lib ./lib
COPY --from=prepare-production /app/build/dependency/META-INF ./META-INF
COPY --from=prepare-production /app/build/dependency/BOOT-INF/classes ./

# Set proper ownership
RUN chown -R javauser:javauser /app

# Switch to non-root user
USER javauser

# Configure container
EXPOSE 8001
VOLUME /tmp

# Health check for container monitoring
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:8001/actuator/health || exit 1

# Use array syntax for ENTRYPOINT
ENTRYPOINT ["java", \
            "-XX:+UseContainerSupport", \
            "-XX:MaxRAMPercentage=75.0", \
            "-cp", ".:lib/*", \
            "com.pam.patientservice.PatientServiceApplication"]
```

## Docker Compose file

```
services:
  patient-service:
    image: patient-service
    container_name: patient-service
    build:
      context: ./general-hosptial-system/patient-service
      target: development
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8001:8001"      # Application port
      - "8081:8081"      # Management port
      - "5005:5005"      # Debug port
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - general-hospital-network

networks:
  general-hospital-network:
    name: general-hospital-network
```

deployment.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: patient-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```
### Build the Docker image:

```bash
docker build -t patient-service .
```

Verify the image was created:

```bash
docker images | grep patient-service
```

Run the container in development mode:

```bash 
docker run -d \
  --name patient-service \
  -p 8001:8001 \
  -p 8081:8081 \
  -p 5005:5005 \
  -e JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" \
  patient-service
```

Check if the container is running:

```bash
docker ps | grep patient-service
```

View container logs:

```bash
docker logs patient-service
```

Check the health status:

```bash
curl http://localhost:8001/actuator/health
```

Stop the container:

```bash
docker stop patient-service
```

Remove the container:

```bash
docker rm patient-service
```

#### Start the service in detatch mode

```bash 
docker-compose up -d
```

#### View logs of the running service
```bash 
docker-compose logs  (-f) patient-service
```
#### Check service status
```bash
docker-compose ps
```
#### Check resource usage
```bash
 docker-compose top
```

#### Check configurations
```bash
docker-compose config
```

#### Stop service
```bash    
docker-compose down
```

#### Start Minikube
```bash
minikube start
```

#### Point Docker CLI to Minikue's Docker daemon
```bash
eval $(minikube docker-env)
```

#### Build the Docker image in Minikube's context
```bash
 docker-compose -t patient-service .
```

#### Apply the deployment
```bash

# Apply both deployment and service
kubectl apply -f patient-service/k8s/

# Run the command below to run on yml file
kubectl apply -f  patient-service/k8s/deployment
```

#### Verify deployment
```bash
# Check deployment status
kubectl get deployments patient-service

# Check pods
kubectl get pods -l app=patient-service

# Check pod details
kubectl describe pod -l app=patient-service
```

#### View logs
```bash
# Get logs from the pod
kubectl logs -l app=patient-service

# Follow logs
kubectl logs -l app=patient-service -f
```

#### Port forward to access the service locally
```bash
# Forward the application port
kubectl port-forward deployment/patient-service 8001:8001

# Forward debug port (in a separate terminal)
kubectl port-forward deployment/patient-service 5005:5005
```

#### Check health
```bash
curl http://localhost:8001/actuator/health
```

#### Clean up
```bash
# Delete deployment
kubectl delete -f deployment.yml

# Stop port forwarding (Ctrl+C in the terminal running port-forward)

# Stop minikube (when done with development)
minikube stop
```

#### Useful troubleshooting commands
```bash
# Get detailed pod information
kubectl get pod -l app=patient-service -o yaml

# Get into the container shell
kubectl exec -it $(kubectl get pod -l app=patient-service -o name) -- /bin/sh

# Check events
kubectl get events --sort-by=.metadata.creationTimestamp

# Check deployment status
kubectl rollout status deployment/patient-service
```

####  Verify service
```bash
# Get service details
kubectl get svc patient-service

# Describe service
kubectl describe svc patient-service

# Get service endpoint
kubectl get endpoints patient-service
```
#### Check service logs
```bash
# Get events related to service
kubectl get events --field-selector involvedObject.kind=Service

# Get pods behind the service
kubectl get pods -l app=patient-service
```

#### Delete service
```bash
# Delete only the service
kubectl delete -f patient-service/k8s/service.yml

# Or delete by name
kubectl delete svc patient-service
```

Remember:

The eval $(minikube docker-env) command needs to be run in each new terminal session
If you're using Docker Desktop, make sure it's running before starting minikube
You might need to run minikube tunnel in a separate terminal if you're using LoadBalancer services
